name: Deploy to Google Cloud Run

on:
    push:
        branches: [post-delivered]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Reconstruct files from secrets
              run: |
                  mkdir -p env
                  # The files are expected to be encoded in base 64, use the base64convert.ps1 to generate the secrets
                  echo "${{ secrets.ENV_B64 }}" | base64 --decode > env/.env
                  echo "${{ secrets.SERVICE_ACCOUNT_B64 }}" | base64 --decode > env/service_account_gmail-agent.json

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  service_account_key: ${{ secrets.GCP_SA_KEY }}
                  export_default_credentials: true

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: '${{ secrets.GCP_SA_KEY }}'

            - name: Configure Docker
              run: gcloud auth configure-docker us-central1-docker.pkg.dev

            - name: Build and Push Docker image
              run: |
                  docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/simetrik-remediation-agent/api:$GITHUB_SHA .
                  docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/simetrik-remediation-agent/api:$GITHUB_SHA

            - name: Deploy to Cloud Run
              run: |
                  gcloud run deploy simetrik-remediation-agent-api \
                    --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/simetrik-remediation-agent/api:$GITHUB_SHA \
                    --region ${{ secrets.GCP_REGION }} \
                    --platform managed \
                    --allow-unauthenticated
